GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/users/0efdcaed-4b57-4d3b-843f-39128fc1c92c HTTP/1.1

###

POST  http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{   
  "name": "diego",
  "email":"diego@gmail.com"
}

###

POST  http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{   
  "name": "",
  "email": ""
}

###

DELETE  http://localhost:3000/users/15accb38-242d-428b-bfc7-d123b7b5a052 HTTP/1.1


